version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_cicd
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
      - "5000:5000"   # ADDED: Flask Backend
      - "8501:8501"   # ADDED: Streamlit Frontend
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: